- hosts: localhost
  connection: local
  become: no
  vars:
    admin_kubeconfig_ca_cert: '{{ lookup("file", "pki/ca.crt") }}'
    admin_kubeconfig_client_cert: '{{ lookup("file", "pki/issued/admin.crt") }}'
    admin_kubeconfig_client_key: '{{ lookup("file", "pki/private/admin.key") }}'
    admin_kubeconfig_server: https://192.168.29.81:6443
  tasks:
    - name: Generate kubeconfig
      template:
        dest: admin.kubeconfig
        src: admin.kubeconfig.j2
