- hosts: localhost
  connection: local
  become: no
  tasks:
    - name: Add label to master node
      tags: k8s_node_config
      loop: "{{ groups.masters }}"
      k8s:
        state: present
        kubeconfig: admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ item }}"
            labels:
              node-role.kubernetes.io/master: ""

    - name: Setup system:kube-apiserver-to-kubelet cluster role
      tags: k8s_auth_config
      k8s:
        state: present
        kubeconfig: admin.kubeconfig
        force: yes
        definition:
          apiVersion: rbac.authorization.k8s.io/v1beta1
          kind: ClusterRole
          metadata:
            annotations:
              rbac.authorization.kubernetes.io/autoupdate: "true"
            labels:
              kubernetes.io/bootstrapping: rbac-defaults
            name: system:kube-apiserver-to-kubelet
          rules:
            - apiGroups:
                - ""
              resources:
                - nodes/proxy
                - nodes/stats
                - nodes/log
                - nodes/spec
                - nodes/metrics
              verbs:
                - "*"

    - name: Assign role system:kube-apiserver-to-kubelet to system:kube-apiserver
      tags: k8s_auth_config
      k8s:
        state: present
        kubeconfig: admin.kubeconfig
        force: yes
        definition:
          apiVersion: rbac.authorization.k8s.io/v1beta1
          kind: ClusterRoleBinding
          metadata:
            name: system:kube-apiserver
            namespace: ""
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: system:kube-apiserver-to-kubelet
          subjects:
            - apiGroup: rbac.authorization.k8s.io
              kind: User
              name: kube-apiserver
