- name: Copy binary
  copy: {src: kube-binaries/kubernetes/server/bin/kube-apiserver, dest: /usr/bin/kube-apiserver, mode: 0755, owner: root, group: root}

- name: Copy sysconfig
  template: {src: kube-apiserver.sysconfig.j2, dest: /etc/sysconfig/kube-apiserver}
  notify: restart kube-apiserver

- name: Copy systemd service
  copy: {src: kube-apiserver.service, dest: /etc/systemd/system/kube-apiserver.service}
  notify: restart kube-apiserver

- name: Ensure /etc/kubernetes present
  file: {path: /etc/kubernetes, state: directory}

- name: Copy encryption-config.yaml
  template: {src: encryption-config.yaml.j2, dest: /etc/kubernetes/encryption-config.yaml}

- name: Copy kube-apiserver CA certificate
  copy: {content: "{{ kube_apiserver_ca_cert }}", dest: /etc/kubernetes/ca.pem}
  notify: restart kube-apiserver

- name: Copy host certificate
  copy: {content: "{{ kube_apiserver_host_cert }}", dest: /etc/kubernetes/host.crt}
  notify: restart kube-apiserver

- name: Copy host key
  copy: {content: "{{ kube_apiserver_host_key }}", dest: /etc/kubernetes/host.key}
  notify: restart kube-apiserver

- name: Copy service-account cert
  copy: {content: "{{ kube_apiserver_service_account_cert }}", dest: /etc/kubernetes/service-account.crt}

- name: Start
  systemd: {state: started, name: kube-apiserver, daemon_reload: yes, enabled: yes}
