- name: Install docker
  yum: {name: docker, state: present}

- name: Configure daemon.json
  template: {src: daemon.json.j2, dest: /etc/docker/daemon.json}
  notify: restart docker

- name: Enable and start
  service: {name: docker, state: started, enabled: yes}
